// <auto-generated />
using System;
using HomeTemperatureSensor.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HomeTemperatureSensor.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20221216152936_novaZaLaptop")]
    partial class novaZaLaptop
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HomeTemperatureSensor.Models.podaci", b =>
                {
                    b.Property<int>("RedniBrojID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("SobaID")
                        .HasColumnType("int");

                    b.Property<string>("StatusAlarma")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("TemperaturaCelzijusa")
                        .HasColumnType("real");

                    b.Property<float>("TemperaturaFarenhajta")
                        .HasColumnType("real");

                    b.Property<DateTime>("Vrijeme")
                        .HasColumnType("datetime2");

                    b.HasKey("RedniBrojID");

                    b.HasIndex("SobaID");

                    b.ToTable("podaci");
                });

            modelBuilder.Entity("HomeTemperatureSensor.Models.sobe", b =>
                {
                    b.Property<int>("SobaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NazivSobe")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SobaID");

                    b.ToTable("sobe");
                });

            modelBuilder.Entity("HomeTemperatureSensor.Models.podaci", b =>
                {
                    b.HasOne("HomeTemperatureSensor.Models.sobe", "soba")
                        .WithMany()
                        .HasForeignKey("SobaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
